cyclomatic_complexity:
    warning: 20
    error: 30
function_body_length:
    warning: 75
    error: 100
file_length:
    warning: 500
    error: 600
type_body_length:
    warning: 300
    error: 400
disabled_rules:
    - function_body_length
    - type_body_length
    - file_length
    - line_length
    - identifier_name
    - cyclomatic_complexity
    - todo
    
